
name: unittest

on:
  workflow_dispatch:
  # Later use workflow on push & release
  push:
    branches: 
      - main

# Jobs
jobs:

  build:
    # Run on ubuntu latest
    runs-on: ubuntu-latest
    
    # Matrix testing
    strategy:
      matrix:
        # Check for all python versions >=3.6
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Install dependencies from freeze
      # TODO: include lint for python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mypy
          pip install -r requirements.txt
      
      # Install package from setup.py and static code analysis
      - name: Static code analysis
        run: |
          mypy setup.py
          python setup.py install
          mypy -p keggtools

      # Build whl and egg
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      
      # Run unittest on installed package
      # - name: Unittest
      #   run: |
      #     pytest
